name = "the-redirector"
type = "javascript"
account_id = ""
api_token = ""
workers_dev = true
kv_namespaces = [
  { binding = "REDIRECTS", id = "", preview_id = "" }
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"
